version: '3'

services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  # crawler:
  #   build: .
  #   volumes:
  #     - .:/app/balder
  #   tty: true
  #   ports:
  #     - 9000:9000
  #   links: 
  #     - mongo
